name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./backend

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      NODE_ENV: test
      MONGO_URL: mongodb://localhost:27017/testdb
      REDIS_URL: redis://localhost:6379
      JWT_SECRET: testsecret
      SESSION_SECRET: testsecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Start MongoDB
        run: |
          sudo apt-get install -y mongodb-org
          sudo mkdir -p /data/db
          sudo chown -R $USER /data/db
          mongod --fork --logpath /var/log/mongod.log --port 27017
          sleep 5

      - name: Run tests
        run: npm test -- --ci --forceExit --detectOpenHandles --testPathPattern=__tests__
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            backend/test-results
            backend/coverage