name: Backend - Node.js Express App Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend - Node.js Express App Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    env:
      NODE_ENV: test
      MONGO_URL: mongodb://localhost:27017/testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-node-modules-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug: List all files in backend
        run: ls -R

      - name: Debug: List files in __tests__ directory
        run: ls -R __tests__

      - name: Run Jest tests (Verbose)
        run: npm test -- --detectOpenHandles --forceExit --coverage --verbose
        env:
          JEST_JUNIT_OUTPUT: test-results/jest/results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-test-results
          path: |
            backend/coverage
            backend/test-results

      - name: Verify server starts
        run: |
          npm run start &
          sleep 10
          curl -f http://localhost:${{ env.PORT }}/health-check || exit 1