name: Node.js CI (Identical to Friend's Setup)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1) Checkout code
      - uses: actions/checkout@v4

      # 2) Setup Node.js (exact version like friend's)
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3) Install backend dependencies (identical approach)
      - name: Install backend deps
        working-directory: ./backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # 4) Start MongoDB (minimal setup like friend's)
      - name: Start MongoDB
        run: |
          sudo mkdir -p /data/db
          sudo chown -R $USER /data/db
          mongod --fork --logpath /var/log/mongod.log --port 27017
          sleep 5

      # 5) Run tests (EXACTLY like friend's - no extra flags)
      - name: Run tests
        working-directory: ./backend
        run: npm test
        env:
          NODE_ENV: test
          MONGO_URL: mongodb://localhost:27017/testdb
          JWT_SECRET: "testsecret"
          SESSION_SECRET: "testsecret"